name: e2e
on: pull_request
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with: { version: 9, run_install: false }
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm preview --port 4173 &
      - run: npx wait-on http://localhost:4173
      - uses: cypress-io/github-action@v6
        with: { command: pnpm cypress run }
